# Generated by Django 3.2.9 on 2021-12-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=100)),
                ('bill_due_date', models.CharField(max_length=100)),
                ('min_payment', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
