# Generated by Django 3.2.9 on 2021-12-02 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_auto_20211130_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='bill_app.profile'),
        ),
    ]
