# Generated by Django 3.2.9 on 2021-12-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0005_alter_bill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('medical', 'medical'), ('utilities', 'utilities'), ('cable/internet', 'cable/internet'), ('subscription', 'subscription'), ('phone', 'phone'), ('credit card', 'credit card'), ('insurance', 'insurance')], default='credit card', max_length=100),
        ),
    ]
